Added functionality for most recent updated field
PDOK/atom-generator pull request #16
Opened 2022-07-13 13:31 UTC by LoekCegeka

# Omschrijving

- Functionaliteit toegevoegd die meest recente datum teruggeeft aan de feed
- Testen aangepast

https://dev.kadaster.nl/jira/browse/PDOK-

## Type verandering

- Nieuwe feature

# Checklist:

- [ ] Ik heb de code in deze PR zelf nogmaals nagekeken
- [ ] Ik heb mijn code beter achtergelaten dan dat ik het aantrof
- [ ] De code is leesbaar en de moeilijke onderdelen zijn voorzien van commentaar
- [ ] Ik heb de tests toegevoegd/uitgebreid indien nodig
- [ ] Ik heb de tests gedraaid die de werking van mijn wijziging bewijst
- [ ] De [PDOK documentatie](https://github.com/PDOK/interne-documentatie) is bijgewerkt indien nodig.
- [ ] Er zit geen gevoelig informatie in deze PR (wachtwoorden etc)

2022-07-13 14:10 UTC, Shalucik requested changes

2022-07-14 05:14 UTC, mwjsanders commented on feeds/feeds.go
> +func (f *Feed) Valid(processedfeed []Feed) error {
Deze wordt nu inderdaad niet meer gebruikt en kan dus weg hier,

2022-07-14 07:08 UTC, LoekCegeka commented on feeds/feeds.go
> +func (f *Feed) Valid(processedfeed []Feed) error {
Hij wordt gebruikt door de valid functie in atom.go 
https://github.com/PDOK/atom-generator/blob/ce8aca1cda16aeaf58329d9d1a37eefbf6f3a7e5/atom.go#L47

2022-07-14 07:15 UTC, Shalucik approved these changes

2022-07-14 07:17 UTC, merged